# Generated by Django 5.0.2 on 2024-04-20 07:22

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allifmaalloginapp', '0001_initial'),
        ('allifmaalusersapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllifmaalUsersModel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('allifmaalcategory', models.CharField(blank=True, choices=[('allifmaaladmin', 'allifmaaladmin'), ('allifmaalowner', 'allifmaalowner'), ('allifmaalstaff', 'allifmaalstaff')], default='allifmaalstaff', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('allifmaalusersapp.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
