# Generated by Django 5.0.2 on 2024-04-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allifmaalcustomusermodel',
            name='timestamp',
        ),
    ]
