# Generated by Django 5.0.2 on 2024-04-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_allifmaalcustomusermodel_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='allifmaalcustomusermodel',
            name='fname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allifmaalcustomusermodel',
            name='lname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
