# Generated by Django 5.0.2 on 2024-04-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_allifmaalcustomusermodel_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allifmaalcustomusermodel',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Mark registered'),
        ),
    ]
