# Generated by Django 5.0.2 on 2024-04-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_allifmaalcustomusermodel_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='allifmaalcustomusermodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='allifmaalcustomusermodel',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Mark admin'),
        ),
    ]
