# Generated by Django 5.0.2 on 2024-04-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_allifmaalcustomusermodel_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allifmaalcustomusermodel',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
