# Generated by Django 5.0.2 on 2024-02-24 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_mymodel_passwrd'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppliersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('company', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='mycon', to='app1.mymodel')),
            ],
        ),
    ]
